### ISSUE TITLE
Disassembling 'rotate right extended' shift operation in second operand

### ISSUE THREAD

**Issue by Papierkorb2292** [jsmolka/disarmv4t#1]
Instructions like `MOV r0, r0, RRX` shift/rotate the value one to the right and copy the carry flag into bit 31. The example instruction would be encoded `E1A00060`, so the shift opcode for "RRX" is "ROR" with the rotation amount being 0.
This type of shift operation is not interpreted correctly by this program and is only disassembled to `mov r0, r0`. 
Instead, if the operation is `ror` and the shift amount is 0, `, rrx` should be appended to the operand.

**Comment by jsmolka** [comment]
I also added the other special shift cases.

```
mov r0, r0
mov r0, r0, rrx
mov r0, r0, lsl 31
mov r0, r0, lsr 32
mov r0, r0, asr 32
```

Now disassembles into:

```
00000000  E1A00000  mov       r0,r0
00000004  E1A00060  mov       r0,r0,rrx
00000008  E1A00F80  mov       r0,r0,lsl 0x1F
0000000C  E1A00020  mov       r0,r0,lsr 0x20
00000010  E1A00040  mov       r0,r0,asr 0x20
```
